name: Release

on:
  # Triggers the workflow after the Test Workflow has completed
  workflow_run:
    workflows: ['Test']
    types:
      - completed
    branches:
      - main
      - next
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-node-
      - name: Install Deps
        run: npm ci --ignore-scripts
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx nx run-many --target=release --all
